{% set name = "jupyterlab-fileopen" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15a71acf852860551fdaef9fcc4baa504070ea98788e9a744c6cc48ecc22440d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - jupyterlab =3
    - jupyter-packaging =0.10
  run:
    - python >=3.6,<4.0
    - jupyterlab =3

test:
  commands:
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyterlab-fileopen/package.json                                                   # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyterlab-fileopen/schemas/jupyterlab-fileopen/jupyterlab-fileopen-settings.json  # [unix]
    - test -f ${PREFIX}/etc/jupyter/jupyter_server_config.d/jupyterlab-fileopen.json                                                   # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-fileopen\\package.json (exit 1)                                 # [win]
    - if not exist %PREFIX%\\etc\\jupyter\\jupyter_server_config.d\\jupyterlab-fileopen.json (exit 1)                                  # [win]

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-fileopen
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A JupyterLab extension that adds a shortcut for opening files using the OS file explorer'
  description: |
    A JupyterLab extension that adds a shortcut for opening files using the OS file explorer
  dev_url: https://github.com/jupyterlab-contrib/jupyterlab-fileopen

extra:
  recipe-maintainers:
    - martinRenou
    - jupyterlab-contrib-bot
